name: Start main process

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
        - name: hello start
          run: echo "run start"
          shell: bash 
        
